name: Documentation CI

on:
  push:
    branches: [ dev ]
    paths:
      - 'server/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 22.x
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    - name: Install dependencies
      run: npm i

    - name: Build API documentation
      run: npm run doc && mv doc/api/v1.html doc/api/index.html

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'doc/api/'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

